### ISSUE TITLE
What is the meaning of the letters and number in the dataset?

### ISSUE THREAD

**Issue by SarahAvatar** [MikeMpapa/CogBeacon-MultiModal_Dataset_for_Cognitive_Fatigue#1]
Really thankful that you gave this data set to the public for research.
I recently do research about fatigue monitoring in reading. There is one question when I viewed your data set.
What is the meaning of the letter such as 'c', 'Aa' and 'as' and the number following in the eeg data?

c 0.0627084970474
Aa 0.234228372574 0.520036458969 0.651266992092 0.749685704708
Ab 0.326684743166 0.376735568047 0.476949155331 0.696061134338
Ad 0.584921419621 0.83384937048 1.04702782631 0.49069827795
Ag 0.111543081701 -0.0502100996673 0.379208028316 0.30519220233
At 0.480908989906 0.665470540524 0.763942658901 0.907416880131
as 0.0689655169845 0.387755095959 0.5 0.590163946152
bs 0.576923072338 0.875 0.280000001192 1.0
ds 0.0 0.102941177785 0.228070169687 0.0
gs 0.9375 0.360000014305 0.962962985039 0.875
ts 0.20000000298 0.232142850757 0.272727280855 0.709677398205

**Comment by SarahAvatar** [comment]
Really thankful that you gave this data set to the public for research.
I recently do research about fatigue monitoring in reading. There is one question when I viewed your data set.
What is the meaning of the letter such as 'c', 'Aa' and 'as' and the number following in the eeg data? 

c 0.0627084970474
Aa 0.234228372574 0.520036458969 0.651266992092 0.749685704708
Ab 0.326684743166 0.376735568047 0.476949155331 0.696061134338
Ad 0.584921419621 0.83384937048 1.04702782631 0.49069827795
Ag 0.111543081701 -0.0502100996673 0.379208028316 0.30519220233
At 0.480908989906 0.665470540524 0.763942658901 0.907416880131
as 0.0689655169845 0.387755095959 0.5 0.590163946152
bs 0.576923072338 0.875 0.280000001192 1.0
ds 0.0 0.102941177785 0.228070169687 0.0
gs 0.9375 0.360000014305 0.962962985039 0.875
ts 0.20000000298 0.232142850757 0.272727280855 0.709677398205

**Comment by MikeMpapa** [comment]
Thanks much for your interest in our work!

Here are the exact meanings:
- 'eeg' corresponds to raw eeg data. From the raw data 5 wavebands are extracted: a,b,d,g,t
- 'a','b','d','g','t' correspond to the relative values of  the wavebands
- Whatever starts with 'A' indicates absolute values of the band shown in the secind letter (ie. At --> Absolute Theta)
-  Whatever ends with 's' indicates the score value of the band (ie as -->Alpha Score)
- 'h' indication of noise in the signal (the lower the value the better the quality of the signal)
- 'c' concentration value provided directly by the muse (unkown formula)

All this metrics were computed on the fly by the Muse. You can find the exact formulas in the paper  (https://www.mdpi.com/2227-7080/7/2/46/htm) or in the README of this git or in the Muse manual (https://web.archive.org/web/20181105231756/http://developer.choosemuse.com/tools/available-data)

*Be sure not to confuse the score_value of the eeg with the score formula that we used to estimate  user preformance

** You can also see the script that captures  and logs the eeg data here: https://github.com/MikeMpapa/CogBeacon-WCST_interface/blob/master/src/MUSE_server.py

The numbers indicate the value for each of the four sensors. First and Last value are for the sensors behind the ears, to middle values for the the sensors in the forehead. Again more details can be found in the paper. See also bellow

![image](https://user-images.githubusercontent.com/12614646/69360995-8e76e280-0c59-11ea-94ed-e98a4cafee3d.png)

**Comment by SarahAvatar** [comment]
Really thank u for the explanation! It's pretty clear!
I think u could add that to the 'readme.md'. Maybe I am not the only one who doesn't understand. (or maybe because I am a green hand hahahaa)
